const data = {
  title: "Frequently Asked Questions",
  rows: [
    {
      title: "How long have you been breeding Aussiedoodles and Sproodles?",
      content: "Now 9 years in with my Aussiedoodles, which I have to tell you is my favorite breed (breed combination, Poodle and Australian Shepherd). The Sproodle (English Spring Spaniel and Poodle) is my second breed that I have been involved in breeding for 5 yrs now and is calmer and not as driven as the Aussiedoodle. I have many years of experience with many other breeds. Back in the late 1990's I used to show (AKC confirmation ring) both a Miniature Pinscher and a Standard Poodle. I also train for therapy work and have certified several dogs which enjoy visiting the nursing home. I still take my dogs to the nursing home, now we go and visit dad/grandpa (the man in the pictures below is my husband's father). I haven't always been a dog breeder, I taught Special Education for 12 years, and have two graduate degrees. I posted more information about my family and myself on my home page if you are interested in knowing who I am and why I do what I do please visit my home page."
    },
    {
      title: "Where do your dogs live? Outside in a kennel?",
      content: "No, when I started my breeding program I was determined to keep everyone in my house (I gave up my dining room so that the dogs had an established area for crates and whelping boxes). It is still this way today, the only change is that I have had to add two additional rooms for the dogs, one of which is a state of the art nursery for older puppies learning to go potty in a designated area. Absolutely no one lives outside. All of my dogs are around my children every day, they are an integral part of our life. We have a noisy, playful house where loud squeals of laughter easily erupt making my puppies and adult dogs very acclimated, as my husband calls it bomb proof. Below is a picture of what used to be my dining room, now it has whelping boxes, parent dogs, and puppies. Please keep in mind that the dogs don't stay locked up as the way it may appear in the picture, I took this picture at bed time when I was making sure everyone is put up for the night. If you read through my website you will find many more pictures that were taken in my home where the dogs are curled up on the couch."
    },
    {
      title: "How old are your parent dogs? How many litters do they have before they retire?",
      content: "My parent dogs don't start breeding until their second or third heat cycle and retire before they turn 4. I don't believe in In Vitro Fertilization (IVF), if they choose not to breed then I honor their decision, and yes this does happen. Some girls retire at a year or two with not having had a litter, my boys typically retire before they turn 4."
    },
    {
      title: "I'm Concerned about raising a puppy",
      content: "This is a very common statement, you're not alone. Many people express their concern with a puppy at night and potty training and crate training, etc. I work diligently to ensure that every puppy has a head start, I want that first night to be a success and every night after that. By the time my puppies leave me they are sleeping through the night in a crate from 10 pm to 7 or 8 am, no accidents/no barking, they are on a schedule for success. If you are concerned about raising a puppy because you work long hours, then my question is how much time do you have to spend with a dog? Just because a puppy requires more time/effort in the beginning, doesn't mean that he/she would enjoy being home alone all day. Every work schedule is different and I am happy to discuss your schedule to see if a puppy can fit. I have also found that families living in close proximity to other families (apartments, condominiums) have a more difficult time initially, due to being concerned that any crying/barking will disturb the neighbors. My parent dogs are all highly trainable and some retire into Therapy or Service Dog homes where they have a special opportunity to be more than just a pet. The offspring of my parent dogs are no different than their parents, outgoing, loyal, loving, intelligent, and easy to train. If you are unsure about a puppy just call me, and plan a visit."
    },
    {
      title: "I'm interested in a retiree",
      content: "My retirees are special to me, most were born here, they have been a part of my family. They are young (under 4), potty trained, crate trained, raised with children, vaccinated, neutered/spade, and get along with cats/dogs. Some of my retirees have more extensive training and will be offered for Service or Therapy Dog placement. To be considered for a retiree you need to call me, and then introduce yourself, tell me about your family and why you believe that an older dog is the best fit. My retirees are not free, I have no reason to give them away, a lot of effort has gone into the raising, training, health testing, etc."
    },
    {
      title: "I want a poodle mix, but I don't want him/her to look like a poodle",
      content: "This has everything to do with grooming. If the groomer shaves the face then the dog will look like a poodle. The preferred clip is the Teddy Bear clip, this is a shorter body coat 1/2 to 1 and a scissored face/ears leaving a more rounded head that has some similarities to a bear. I actually make mention to this on another part of my website, my sons don't like the feel of a hairy face so I always had to shave my boy Max's face. My children all have sensory problems, so the ticklish, sometimes wet face of a poodle or poodle cross is just to much overload, so I would shave the face. When Max was groomed this way he was mistaken for a poodle, it's all in the grooming."
    },
    {
      title: "I noticed that you breed Aussiedoodles and Sproodles, do you breed anything else, do you have experience with other poodle cross combinations?",
      content: "Yes, I started with Aussiedoodles, but have bred several other breeds and raised and trained many others. When considering a Poodle cross it is best to consider the temperament of both breeds involved. The Australian Shepherd is a herding breed with superior intelligence and a very high drive, mixed with the Poodle you tone down the drive and have a more hypoallergenic coat. The Aussiedoodle is quick to learn and they tend to mature more quickly, they are active and love children. The Sproodle is quite different from the Aussiedoodle. The Sproodle is a Poodle combined with an English Springer Spaniel, though still very trainable they only desire to make their family happy. The Sproodle is easy to crate/potty train and thrives on human interaction, silly, loyal, and they tend to want to be a lap dog (40 lbs doesn't make a good lap dog). The Sproodle has far less drive to work than the Aussiedoodle. I have also started a Goldendoodle line that is the moyen/small standard size (under 50 lbs). Well, I don't have my Goldendoodle parents (mothers), my nephew and his family have raised and now breed my Goldendoodle line. I have the father that is used in the breeding, both parents are fully health tested. The Goldendoodle is slower to mature, sweet temperament, desire to please, but not big on hard work (at least not in the first 2 yrs). They are happy go lucky, friendly and make a great companion dog. Contact me to see when his next litter of Goldendoodles will be due. In the past I bred Sheepadoodles (Old English Sheepdog and Poodle), they are larger, slower to mature, and a bit too silly/immature for much longer than the other breeds I have experience with. I have also RAISED/TRAINED the following Poodle crosses; Giant Schnoodle (Giant Schnauzer and Poodle), Flandoodle (Bouvier Des Flanders and Poodle), and Shepadoodle (German Shepherd and Poodle). My experience is not limited to Poodles and Poodle crosses, I have raised and trained many other breeds. I am happy to discuss the different breed combinations with you and help direct you to the breed that best suits your family."
    },
    {
      title: "How often does my puppy/dog need to be groomed?",
      content: "This is dependent upon how you want your dog to look and how much grooming you want to do. If you want to keep a nice coat of 1-2in. then you should expect to brush for 10 min daily and a complete grooming every 5-6 weeks. If you shave the dog all the way down (summer cut) then he/she can go 7-8 weeks before the next full grooming. However, the ears need additional care. "
    },
    {
      title: "Ear Care?",
      content: "All Poodles and most Poodle crosses have hairs that grow out of their ears, many times the hairs originate in the deepest part of the ear. This hair needs to be removed and the ears kept clean and dry. To achieve this the hair needs to be pulled or plucked out, many groomers use hemostats to accomplish this in a quick manner similar to having your brow waxed. I do not use hemostats, I teach each puppy to lay in my lap while I gently pull hairs out using just my fingers. It takes longer than just pulling everything at once, but they tolerate it and almost seem to know that it's good for them. My adults will easily stand at my side to have their ears done. Hair that's growing in the ear is slippery and will slide right through your fingers, I use an ear powder that I sprinkle on the hairs that need to be pulled out. I start from the outer ear and work my way in. I am happy to demonstrate this to you when you are getting ready to take a puppy home, I can even clean your puppy's ears in front of you on the day you pick up, no worries I'm flexible and this is one area that is important to your new best friend."
    },
    {
      title: "How often should I give my puppy a bath?",
      content: "Only as often as necessary, over washing is hard on a dog's skin. Typically you should only need to give a bath one time inbetween full grooming dates. Now obviously if your dog has been running in the mud and is dirty then you would need to give him/her a bath. Stay away from heavy blow drying as this is harsh and unnecessary. I bath the puppies in my bath tub and use a detachable sprayer to get them wet, I also place a bath towel or rubber bath mat in the tub to prevent them from slipping. If you suspect fleas then you should use dawn dish soap, it kills fleas instantly. Dawn burns the eyes and should not be used on the head, instead make a ring of dawn around the neck and work toward the tail, lather up with dawn and wait 5 minutes before rinsing. Dawn soap is harder to rinse out, so rinse several times. Some puppies may want to play in the tub, this behavior should be discouraged as you wouldn't want an adult dog jumping/playing in the tub, so don't reward the behavior. If you don't suspect fleas then I recommend that you use either Johnson's Baby Soap (tearless) or a tearless puppy shampoo, a soap that can be used on the face. Smell it before you buy it, nothing's worse than buying a soap that you don't like and now your best friend has that smell all over him."
    },
    {
      title: "Do they like water?",
      content: "Only as often as necessary, over washing is hard on a dog's skin. Typically you should only need to give a bath one time inbetween full grooming dates. Now obviously if your dog has been running in the mud and is dirty then you would need to give him/her a bath. Stay away from heavy blow drying as this is harsh and unnecessary. I bath the puppies in my bath tub and use a detachable sprayer to get them wet, I also place a bath towel or rubber bath mat in the tub to prevent them from slipping. If you suspect fleas then you should use dawn dish soap, it kills fleas instantly. Dawn burns the eyes and should not be used on the head, instead make a ring of dawn around the neck and work toward the tail, lather up with dawn and wait 5 minutes before rinsing. Dawn soap is harder to rinse out, so rinse several times. Some puppies may want to play in the tub, this behavior should be discouraged as you wouldn't want an adult dog jumping/playing in the tub, so don't reward the behavior. If you don't suspect fleas then I recommend that you use either Johnson's Baby Soap (tearless) or a tearless puppy shampoo, a soap that can be used on the face. Smell it before you buy it, nothing's worse than buying a soap that you don't like and now your best friend has that smell all over him."
    },
    {
      title: "Do you health test the parent dogs? What genetic testing has been completed?",
      content: "Yes, I have completed individual panels to ensure the genetic health of puppies produced while under my care. My dogs are all negative for the MDR1 gene mutation (only a concern with the Aussiedoodles as the gene mutation comes from the Australian Shepherd).  The MDR1 or Multi-Drug Resistance gene causes sensitivity to Ivermectin, Loperamide, and several other drugs. Ivermectin is used in all heart worm medications and this gene mutation can be fatal if heart worm medication/prevention is given to a dog/puppy that has the mutation. I have also tested my dogs for Progressive Retinal Atrophy (PRA) and Progressive Rod-Cone Degeneration (PRCD) these are eye disorders common in many breeds that can cause the dog to become blind at a young age. They are also tested for Degenerative Myelopathy (DM) which is an incurable, progressive disease of the spinal cord. My parent dogs are all double negative for these disorders, this means that they don't have the disease and they don't carry the genetic mutation for it, therefor they can't produce affected offspring. I have also tested my dogs for Von Willebrand's Disease (VWD) a clotting disease common to the poodle and is similar to hemophilia in humans. All of my dogs are double negative. I do my very best to produce the healthiest puppies possible. Presently I have not completed x-rays for hips/elbows, several reasons for this. First, my dogs are not large, orthopedic issues typically exist in the larger breeds (50+ lbs) with the rate of hip dysplasia being much lower in dogs less than 50 lbs. Second, my outside parent lines came from show breeders where the parent dogs were titled and all health testing completed (including hips/elbows). Last, I'm trying to keep my price down, quality up, and still get to retire everyone at a young age, the OFA certification has to be done after the dog's second birthday, expensive and requires a veterinarian that has experience in imagery for OFA. For the moment I intend to keep things the way they are. I have hard copies of all completed genetic tests, I will not post them here, if you want to see the test results or would like a copy of the parent genetic testing with your puppy please ask. I am choosing not to post my test results as I have had my photographs stolen from my website previously, sad but true."
    },
    {
      title: "How can I get on a reservation list? Can I visit?",
      content: "If you think that you want a puppy from me then you need to give me a call and we can discuss my current puppies, up coming litters, and what you think will best fit your family. I will send you multiple (10+) videos so that you can see where my dogs play/live, how I raise my puppies, and what my past puppies are like now all grown up. Visitation is when the puppies are 6-7 wks old, after they have received their first set of vaccinations and it is time to choose your puppy. Aside from the videos that I send you I also have a YouTube channel, just search my name Robin Crubaugh on YouTube and you will find my videos."
    },
    {
      title: "What should I know prior to visiting?",
      content: "Please prior to scheduling with me make sure that your family is on board and it's preferred that all family members that will be involved in raising the puppy visit as well. You will need to plan for the drive, I am two hours North of Atlanta in Union County (Blairsville) where the highest elevation can be found. Our county is well known for it's waterfalls, hiking, and boating (Lake Nottely), we refer to it as Mayberry. Once here to meet dogs/puppies you should expect to visit for at least one hour, often times even longer. My mornings are typically very busy and having first time visitors early is almost impossible, I prefer that you plan to visit at 10 am or later. Other things that I ask, please don't visit anyone else's puppies, or the pet store, or the rescue/shelter just prior to visiting me (I take great caution in keeping my puppies safe, I don't need to take any risks of bringing disease/germs in). I also ask that if you have an existing dog that you not bring him/her for this visit. The only time that I ask someone to bring their dog is when you are considering a retiree, in which case we will meet at a neutral location (local park). If you or someone in the family is sick I ask that you let me know, I have a child and husband with a compromised immune system and will take extra precautions. Please keep in mind that you are visiting my personal home, our personal space, you will be able to meet parents and puppies while visiting, but we will meet everyone outside. Please plan to stop for gas/food/restroom prior to visiting. Consider weather/temperature when visiting me, we are much cooler than Atlanta and get a fair amount of snow in the winter. My town is a picturesque place to visit, hiking, restaurants, etc, if you are planning to visit and want to know where to hike or where to eat please ask, we've been here for 14 years now and can direct you to where the locals go. A few pictures taken of the scenery here in Blairsville."
    },
    {
      title: "When can I choose my puppy?",
      content: "You can choose your puppy after they have turned 6 weeks. They receive their first set of vaccinations at 6 wks and can be visited after that. The true temperament of a puppy is most clear when the puppy is 6 wks and older, you should not choose a puppy based on color only. If you are solely interested in one color one gender (I only want a blue merle girl with blue eyes) then you should expect to wait longer for that exact color combination. While I may produce that exact scheme from time to time I can't guarantee it, it could take a while for me to have exactly what you are looking for. Colors change, what might be born black can change to silver in the first year. To see this color change visit my before and after pics page. Puppy selection takes place after the puppies have turned 6 weeks and then each family is scheduled in the order of the reservation list (this process typically takes several days with most families visiting on different days). If you live far away and can't make the trip then I will work with you. I can send pictures/videos, facetime, and provide individual puppy temperament descriptions to assist you in making a decision."
    },
    {
      title: "Male vs Female",
      content: "This is something that I get asked about often, and unfortunately there is a typical perception that male dogs are going to lift and mark everywhere even inside of the home. This perception is just not accurate and honestly goes back to training or lack there of. My greatest example is my oldest boy, Max, that was a breeding dog for four years, he doesn't lift/mark in my house and he never has. If you research the gender preference for service work or Police work or protection work you will find that male dogs hold more of those jobs over female dogs. Ever wonder why? Male dogs typically are more interested in pleasing their owners, they are velcro, they want to be with and work for their owners. Not that females are drastically different, but they tend to be more independent due to their natural ability to raise a litter of puppies without any help. Going back to the whole leg lifting behavior that some people are concerned about. If you put your dog in the back yard (without supervision) and you leave him or her out there for an extended period of time 2+ hrs you risk teaching your dog to run around and mark. When left alone in the back yard they are prone to feel a need to mark the perimeter to signal to the neighboring dogs that this yard is not for any other dog. The second mistake made is while taking your dog for a walk, while on a walk you should not allow your dog to stop at every bush, mailbox, etc, this is teaching the dog that they should mark. A walk needs to be pleasurable for both the dog and the owner, I recommend that you take treats (cooked chicken) and that the walk is a time to train for the desired behaviors."
    },
    {
      title: "I am concerned about shedding, we have allergies and asthma, do the puppies shed?",
      content: "Some puppies may shed, while others will be more hypoallergenic. For allergy sufferers I suggest that you choose a breed combination where there is more poodle in the lines (example; Aussiedoodle bred back to a poodle). There is a much greater likelihood of shedding with a first generation cross. Since you won't actually choose your puppy until they are 6 weeks of age, it is much easier to evaluate older puppies for shedding and be able to identify the puppies that are hypoallergenic."
    },
    {
      title: "What does my puppy come with?",
      content: "All puppies receive Two sets of vaccinations (both are 5 way), Microchipped, First dose of heart-worm/flea prevention (Revolution), Two year health guarantee, Probiotic powder (two week supply to get you started), Training info, My Puppy Manual (written by me), Small bag of cedar shavings (to help generalize the potty area), Newspaper (for crate training), Natural Bone, clicker for training, and a tennis ball. All puppies have a head start when it comes to training. They are all part of my head start potty training program and begin with their first exposure to potty training at just four weeks. I have many videos of my puppies at four weeks being successful at potty training, it still amazes me. I end my training with the puppies on the last week with exposure to the crate and focus on each puppy being able to sleep in a crate through the night. I also groom my puppies throughout the raising process and all puppies have clean ears, trimmed nails, sanitary area clipped, and trimmed face. When you buy a puppy from me expect to stay in touch, send pictures from time to time, and please I am here to help, I am an expert at raising puppies and can easily provide assistance with any questions or concerns you have. I truly enjoy hearing from my puppy owners."
    },
    {
      title: "How much do you sell your puppies for?",
      content: "Solid black is $2000, and all other colors are $2500. Keep in mind that color is only one aspect of each puppy. All of my puppies come with a two year genetic guarantee (parents dogs are health tested), two sets of vaccinations, microchipped, first dose of heartworm/flea prevention (Revolution), and initial potty/crate training has been started. Not sure if I'm the breeder for you check out my YouTube channel, you can find me on YouTube by searching my name (Robin Crubaugh)."
    },
    {
      title: "Do you sell your puppies with registration papers?",
      content: "My parent dogs are registered and while I have the ability to sell the puppies with registration papers I chose not to do so. My dogs live inside, not in a kennel, and I don't want to support breeding establishments where the dogs live outside in a kennel on concrete floors. This is not for me nor is it for my dogs. I also don't place any of my puppies in guardian homes and I don't stud out to someone else's dog."
    },
    {
      title: "What do you feed your parent dogs and puppies?",
      content: "I feed my dogs and puppies various dry kibble formulas. The latest research indicates that dogs fed the same food day after day and year after year that the dog will suffer from issues related to the food like allergies. I feed mine several different brands for various reasons, I use a Salmon and Potato formula, and a chicken and rice formula and a lamb and oatmeal formula. My puppies are fed a puppy formula that has multiple proteins (chicken, duck, salmon, and herring). I also provide my dogs with probiotics, raw eggs, and salmon oil. Everyone is fed on a rotating schedule; Monday probiotic, Tuesday raw egg, Wednesday salmon oil, and then back to the beginning with Thursday probiotic, etc. They are fed twice per day with the supplement meal (larger meal) in the morning and a second meal of dry kibble only in the evening. I have included pictures of the probiotic and salmon oil that I use, I have also included pictures demonstrating how to mix raw egg (shell and all) in their dry kibble. I am frequently asked about the raw diet, which I have tried and love, but it has its drawbacks. When feeding only raw (chicken/turkey, whole parts, leg/thigh with skin bones and all) I found that my dogs seemed happier with meal time, their coat/skin was perfect, and the output was not as plentiful or smelly. However, due to the messiness (meat remnants on the face and paws) there is a risk of salmonella being spread through the house. A canine's digestive system is different from ours and salmonella is not problematic for them, so the raw diet is safe for them (yes bones and all, uncooked). One other thing to take note of, should you decide to go the route of raw, never mix kibble and raw together (not even different meals/times). You should feed a diet of either all kibble or all raw."
    },
    {
      title: "Where can I buy the dog food that you use? I want to keep my puppy on the same food",
      content: "The dog food that I use is Life's Abundance, the Small and Medium Breed Puppy formula. This food can't be purchased in a store it is only available to purchase on-line. This is the highest quality food for the price that I have found so far. The greatest value to this food is the different proteins (chicken, duck, salmon, and herring). The food also has a higher level of taurine, which many brands don't even list. Not having enough taurine in the food has been linked to Dilated Cardiomyopathy (DCM), yet the organization that oversees our dog foods, the Association of American Food Control Officials (AAFCO), does not require taurine in dog food. Please use my direct link to Life's Abundance to purchase your bag of the Small and Medium Breed Puppy formula. If the website doesn't automatically come up, please copy and paste the link to the address bar www.lifesabundance.com/bigdoodledreams"
    },
    {
      title: "What do you use for treats and toys?",
      content: "I prefer toys that can't be destroyed/consumed, toys with the least risk of injury to the dog/puppy. My favorite is a natural/raw soup bone purchased at the local grocery store. The soup bone can only be chewed on raw for a matter of a couple of days, then it will need to be cleaned for further use. After a dog/puppy has chewed on the soup bone for a couple of days it will need to be rinsed off with running tap water (hot) and a knife to scrape off any meat/marrow, then place it in a bucket of bleach/water to soak for a few hours. Then rinse again with hot tap water and soak in soapy water, rinse and set out to dry. After you have gone through these steps you end up with a beautiful white bone that can be used over and over. Now hollow and clean you can add a little peanut butter to the inside of the bone. Pictures below showing the soup bones before and after. Other bones/toys I like are the Nyla bones, Galileo bones, and Kong toys. Toys that initiate tug of war should be completely avoided. Toys that can be destroyed carry a risk and should only be provided during structured/supervised play time. I'm not a big fan of processed treats, so if you are using treats for training I recommend cooked chicken diced up."
    }
  ]
};

export default data;
